### ISSUE TITLE
Changing search websites doesn't survive Chrome restart

### ISSUE THREAD

**Issue by marcinbarczynski** [Juuso-H/hotkeys-for-search#1]
Great extension, but when I change search websites, they all go back to defaults after restarting Chrome.
I'm using Chrome 81.0.4044.92 on Ubuntu.

**Comment by Juuso-H** [comment]
The issue should now be fixed. Thanks a lot for taking the time to report this! :)

**Comment by marcinbarczynski** [comment]
Thank you. Now it's working!
